[package]
name = "an-operating-system-in-rust"
version = "0.1.0"
authors = ["Tomoya Tabuchi <t@tomoyat1.com>"]
edition = "2018"

[dependencies]
rlibc = "1.0"
uefi = "0.5.0"
bootlib = { path = "./bootlib" }

[workspace]
members = [
    "bootloader",
    "bootlib",
]
