[package]
name = "an-operating-system-in-rust"
version = "0.1.0"
authors = ["tomoyat1 <t@tomoyat1.com>"]
edition = "2018"

[dependencies]
compiler_builtins = { git = "https://github.com/rust-lang/compiler-builtins" }
log = { version = "0.4", default-features = false }
uefi = "0.4.7"
uefi-services = "0.2.4"
array-macro = "1.0.5"
