[package]
name = "bootloader"
version = "0.1.0"
authors = ["tomoyat1 <t@tomoyat1.com>"]
edition = "2018"

[dependencies]
log = { version = "0.4", default-features = false }
uefi = "0.5.0"
uefi-services = "0.2.5"
array-macro = "1.0.5"
rlibc = "1"
